// Dalhousie University — Complete Course Database
// Organized by Faculty
const DAL_COURSES = [

  // ══════════════════════════════════════════
  // FACULTY OF AGRICULTURE
  // ══════════════════════════════════════════
  { code:'AGRI 1000', name:'Introduction to Agriculture',                   faculty:'Agriculture' },
  { code:'AGRI 1001', name:'Agriculture and Society',                       faculty:'Agriculture' },
  { code:'AGRI 2000', name:'Crop Science',                                  faculty:'Agriculture' },
  { code:'AGRI 2001', name:'Soil Science Fundamentals',                     faculty:'Agriculture' },
  { code:'AGRI 2500', name:'Agricultural Economics',                        faculty:'Agriculture' },
  { code:'AGRI 3000', name:'Farm Management',                               faculty:'Agriculture' },
  { code:'AGRI 3001', name:'Sustainable Agriculture',                       faculty:'Agriculture' },
  { code:'AGRI 3500', name:'Agricultural Policy',                           faculty:'Agriculture' },
  { code:'AGRI 4000', name:'Advanced Crop Production',                      faculty:'Agriculture' },
  { code:'AGRI 4500', name:'Agricultural Research Methods',                 faculty:'Agriculture' },
  { code:'ANSC 1001', name:'Introduction to Animal Science',                faculty:'Agriculture' },
  { code:'ANSC 2001', name:'Animal Nutrition',                              faculty:'Agriculture' },
  { code:'ANSC 2002', name:'Animal Physiology',                             faculty:'Agriculture' },
  { code:'ANSC 2003', name:'Livestock Management',                          faculty:'Agriculture' },
  { code:'ANSC 3001', name:'Animal Genetics',                               faculty:'Agriculture' },
  { code:'ANSC 3002', name:'Dairy Science',                                 faculty:'Agriculture' },
  { code:'ANSC 3003', name:'Poultry Science',                               faculty:'Agriculture' },
  { code:'ANSC 4001', name:'Advanced Animal Nutrition',                     faculty:'Agriculture' },
  { code:'ANSC 4002', name:'Animal Breeding',                               faculty:'Agriculture' },
  { code:'FOSC 2001', name:'Food Chemistry',                                faculty:'Agriculture' },
  { code:'FOSC 2002', name:'Food Microbiology',                             faculty:'Agriculture' },
  { code:'FOSC 3001', name:'Food Processing Technology',                    faculty:'Agriculture' },
  { code:'FOSC 3002', name:'Food Safety and Quality',                       faculty:'Agriculture' },
  { code:'FOSC 4001', name:'Advanced Food Science',                         faculty:'Agriculture' },
  { code:'FOSC 4002', name:'Food Product Development',                      faculty:'Agriculture' },
  { code:'PLSC 2001', name:'Plant Physiology',                              faculty:'Agriculture' },
  { code:'PLSC 2002', name:'Horticulture',                                  faculty:'Agriculture' },
  { code:'PLSC 3001', name:'Plant Pathology',                               faculty:'Agriculture' },
  { code:'PLSC 3002', name:'Weed Science',                                  faculty:'Agriculture' },
  { code:'PLSC 4001', name:'Plant Breeding',                                faculty:'Agriculture' },
  { code:'SOIL 2001', name:'Soil Fertility',                                faculty:'Agriculture' },
  { code:'SOIL 3001', name:'Soil Chemistry',                                faculty:'Agriculture' },
  { code:'SOIL 4001', name:'Advanced Soil Science',                         faculty:'Agriculture' },

  // ══════════════════════════════════════════
  // FACULTY OF ARCHITECTURE & PLANNING
  // ══════════════════════════════════════════
  { code:'ARCH 1010', name:'Architectural Design I',                        faculty:'Architecture & Planning' },
  { code:'ARCH 1020', name:'Architectural Design II',                       faculty:'Architecture & Planning' },
  { code:'ARCH 2010', name:'Architectural History I: Ancient to Renaissance',faculty:'Architecture & Planning' },
  { code:'ARCH 2020', name:'Architectural History II: Modern Architecture', faculty:'Architecture & Planning' },
  { code:'ARCH 2030', name:'Structural Systems in Architecture',            faculty:'Architecture & Planning' },
  { code:'ARCH 2040', name:'Environmental Systems',                         faculty:'Architecture & Planning' },
  { code:'ARCH 3010', name:'Advanced Architectural Design I',               faculty:'Architecture & Planning' },
  { code:'ARCH 3020', name:'Advanced Architectural Design II',              faculty:'Architecture & Planning' },
  { code:'ARCH 3030', name:'Building Technology',                           faculty:'Architecture & Planning' },
  { code:'ARCH 3040', name:'Architectural Theory',                          faculty:'Architecture & Planning' },
  { code:'ARCH 4010', name:'Design Studio: Urban Housing',                  faculty:'Architecture & Planning' },
  { code:'ARCH 4020', name:'Urban Design',                                  faculty:'Architecture & Planning' },
  { code:'ARCH 4030', name:'Professional Practice',                         faculty:'Architecture & Planning' },
  { code:'EVDS 2001', name:'Introduction to Environmental Design',          faculty:'Architecture & Planning' },
  { code:'EVDS 3001', name:'Landscape Architecture',                        faculty:'Architecture & Planning' },
  { code:'EVDS 4001', name:'Environmental Design Studio',                   faculty:'Architecture & Planning' },
  { code:'PLAN 2001', name:'Introduction to Planning',                      faculty:'Architecture & Planning' },
  { code:'PLAN 2002', name:'Urban and Regional Planning',                   faculty:'Architecture & Planning' },
  { code:'PLAN 3001', name:'Land Use Planning',                             faculty:'Architecture & Planning' },
  { code:'PLAN 3002', name:'Housing Policy',                                faculty:'Architecture & Planning' },
  { code:'PLAN 4001', name:'Planning Law and Administration',               faculty:'Architecture & Planning' },
  { code:'PLAN 4002', name:'Community Development',                         faculty:'Architecture & Planning' },

  // ══════════════════════════════════════════
  // FACULTY OF ARTS & SOCIAL SCIENCES
  // ══════════════════════════════════════════
  // Classics
  { code:'CLAS 1000', name:'Greek and Roman Civilization',                  faculty:'Arts & Social Sciences' },
  { code:'CLAS 2000', name:'Greek Literature in Translation',               faculty:'Arts & Social Sciences' },
  { code:'CLAS 2001', name:'Roman Literature in Translation',               faculty:'Arts & Social Sciences' },
  { code:'CLAS 3000', name:'Ancient Philosophy',                            faculty:'Arts & Social Sciences' },
  { code:'CLAS 4000', name:'Advanced Topics in Classics',                   faculty:'Arts & Social Sciences' },
  // Economics
  { code:'ECON 1101', name:'Introductory Microeconomics',                   faculty:'Arts & Social Sciences' },
  { code:'ECON 1102', name:'Introductory Macroeconomics',                   faculty:'Arts & Social Sciences' },
  { code:'ECON 2200', name:'Intermediate Microeconomics',                   faculty:'Arts & Social Sciences' },
  { code:'ECON 2201', name:'Intermediate Macroeconomics',                   faculty:'Arts & Social Sciences' },
  { code:'ECON 2220', name:'Economic Statistics',                           faculty:'Arts & Social Sciences' },
  { code:'ECON 2230', name:'Introductory Econometrics',                     faculty:'Arts & Social Sciences' },
  { code:'ECON 3300', name:'Public Finance',                                faculty:'Arts & Social Sciences' },
  { code:'ECON 3310', name:'Labour Economics',                              faculty:'Arts & Social Sciences' },
  { code:'ECON 3320', name:'Industrial Organization',                       faculty:'Arts & Social Sciences' },
  { code:'ECON 3330', name:'International Trade',                           faculty:'Arts & Social Sciences' },
  { code:'ECON 3340', name:'Development Economics',                         faculty:'Arts & Social Sciences' },
  { code:'ECON 3350', name:'Environmental Economics',                       faculty:'Arts & Social Sciences' },
  { code:'ECON 3360', name:'Health Economics',                              faculty:'Arts & Social Sciences' },
  { code:'ECON 4400', name:'Advanced Microeconomics',                       faculty:'Arts & Social Sciences' },
  { code:'ECON 4401', name:'Advanced Macroeconomics',                       faculty:'Arts & Social Sciences' },
  { code:'ECON 4420', name:'Advanced Econometrics',                         faculty:'Arts & Social Sciences' },
  { code:'ECON 4430', name:'Game Theory',                                   faculty:'Arts & Social Sciences' },
  // English
  { code:'ENGL 1000', name:'Academic Reading and Writing',                  faculty:'Arts & Social Sciences' },
  { code:'ENGL 1001', name:'Introduction to Literature',                    faculty:'Arts & Social Sciences' },
  { code:'ENGL 1010', name:'Introduction to Literature: Fiction',           faculty:'Arts & Social Sciences' },
  { code:'ENGL 1020', name:'Introduction to Literature: Poetry',            faculty:'Arts & Social Sciences' },
  { code:'ENGL 2000', name:'Studies in British Literature',                 faculty:'Arts & Social Sciences' },
  { code:'ENGL 2001', name:'Studies in American Literature',                faculty:'Arts & Social Sciences' },
  { code:'ENGL 2002', name:'Studies in Canadian Literature',                faculty:'Arts & Social Sciences' },
  { code:'ENGL 2100', name:'Creative Writing: Fiction',                     faculty:'Arts & Social Sciences' },
  { code:'ENGL 2200', name:'Shakespeare',                                   faculty:'Arts & Social Sciences' },
  { code:'ENGL 2300', name:'Film Studies',                                  faculty:'Arts & Social Sciences' },
  { code:'ENGL 2400', name:'Introduction to Literary Theory',               faculty:'Arts & Social Sciences' },
  { code:'ENGL 3000', name:'Advanced Literary Theory',                      faculty:'Arts & Social Sciences' },
  { code:'ENGL 3100', name:'Creative Writing: Poetry',                      faculty:'Arts & Social Sciences' },
  { code:'ENGL 3200', name:'Postcolonial Literature',                       faculty:'Arts & Social Sciences' },
  { code:'ENGL 3300', name:'Victorian Literature',                          faculty:'Arts & Social Sciences' },
  { code:'ENGL 3400', name:'Contemporary Fiction',                          faculty:'Arts & Social Sciences' },
  { code:'ENGL 4200', name:'Advanced Studies in Modern Literature',         faculty:'Arts & Social Sciences' },
  { code:'ENGL 4300', name:'Studies in World Literature',                   faculty:'Arts & Social Sciences' },
  // French
  { code:'FREN 1000', name:'Introductory French I',                         faculty:'Arts & Social Sciences' },
  { code:'FREN 1001', name:'Introductory French II',                        faculty:'Arts & Social Sciences' },
  { code:'FREN 2000', name:'Intermediate French I',                         faculty:'Arts & Social Sciences' },
  { code:'FREN 2001', name:'Intermediate French II',                        faculty:'Arts & Social Sciences' },
  { code:'FREN 3000', name:'Advanced French Grammar and Composition',       faculty:'Arts & Social Sciences' },
  { code:'FREN 3001', name:'French Literature: 19th Century',               faculty:'Arts & Social Sciences' },
  { code:'FREN 4000', name:'Advanced French Literature',                    faculty:'Arts & Social Sciences' },
  // Gender & Women's Studies
  { code:'GWST 1000', name:'Introduction to Gender and Women\'s Studies',   faculty:'Arts & Social Sciences' },
  { code:'GWST 2000', name:'Feminist Theory',                               faculty:'Arts & Social Sciences' },
  { code:'GWST 3000', name:'Gender, Race and Class',                        faculty:'Arts & Social Sciences' },
  { code:'GWST 4000', name:'Advanced Topics in Gender Studies',             faculty:'Arts & Social Sciences' },
  // History
  { code:'HIST 1001', name:'Western Civilization I: Ancient to Early Modern',faculty:'Arts & Social Sciences' },
  { code:'HIST 1002', name:'Western Civilization II: Modern Era',           faculty:'Arts & Social Sciences' },
  { code:'HIST 2010', name:'Canadian History I: to Confederation',          faculty:'Arts & Social Sciences' },
  { code:'HIST 2011', name:'Canadian History II: Post-Confederation',       faculty:'Arts & Social Sciences' },
  { code:'HIST 2100', name:'History of the Atlantic Provinces',             faculty:'Arts & Social Sciences' },
  { code:'HIST 2200', name:'Modern Europe 1789 to Present',                 faculty:'Arts & Social Sciences' },
  { code:'HIST 2300', name:'History of the United States',                  faculty:'Arts & Social Sciences' },
  { code:'HIST 2400', name:'World History since 1500',                      faculty:'Arts & Social Sciences' },
  { code:'HIST 3010', name:'Atlantic Canada: Economy and Society',          faculty:'Arts & Social Sciences' },
  { code:'HIST 3200', name:'History of Modern Science',                     faculty:'Arts & Social Sciences' },
  { code:'HIST 3300', name:'Imperialism and Colonialism',                   faculty:'Arts & Social Sciences' },
  { code:'HIST 4010', name:'Research Seminar in Canadian History',          faculty:'Arts & Social Sciences' },
  // International Development Studies
  { code:'INTD 1000', name:'Introduction to International Development',     faculty:'Arts & Social Sciences' },
  { code:'INTD 2000', name:'Development Theory',                            faculty:'Arts & Social Sciences' },
  { code:'INTD 3000', name:'Global Political Economy',                      faculty:'Arts & Social Sciences' },
  { code:'INTD 4000', name:'Development Practice',                          faculty:'Arts & Social Sciences' },
  // Music
  { code:'MUSI 1000', name:'Introduction to Music',                         faculty:'Arts & Social Sciences' },
  { code:'MUSI 1100', name:'Music Theory I',                                faculty:'Arts & Social Sciences' },
  { code:'MUSI 1101', name:'Music Theory II',                               faculty:'Arts & Social Sciences' },
  { code:'MUSI 2000', name:'Music History I: Medieval to Baroque',          faculty:'Arts & Social Sciences' },
  { code:'MUSI 2001', name:'Music History II: Classical to Romantic',       faculty:'Arts & Social Sciences' },
  { code:'MUSI 3000', name:'Advanced Music Theory',                         faculty:'Arts & Social Sciences' },
  { code:'MUSI 3100', name:'Music Composition',                             faculty:'Arts & Social Sciences' },
  { code:'MUSI 4000', name:'Senior Recital',                                faculty:'Arts & Social Sciences' },
  // Philosophy
  { code:'PHIL 1050', name:'Critical Thinking',                             faculty:'Arts & Social Sciences' },
  { code:'PHIL 1060', name:'Introduction to Ethics',                        faculty:'Arts & Social Sciences' },
  { code:'PHIL 1080', name:'Introduction to Philosophy',                    faculty:'Arts & Social Sciences' },
  { code:'PHIL 2010', name:'Logic',                                         faculty:'Arts & Social Sciences' },
  { code:'PHIL 2020', name:'Theory of Knowledge',                           faculty:'Arts & Social Sciences' },
  { code:'PHIL 2030', name:'Philosophy of Religion',                        faculty:'Arts & Social Sciences' },
  { code:'PHIL 2060', name:'Social and Political Philosophy',               faculty:'Arts & Social Sciences' },
  { code:'PHIL 3010', name:'Philosophy of Science',                         faculty:'Arts & Social Sciences' },
  { code:'PHIL 3020', name:'Philosophy of Mind',                            faculty:'Arts & Social Sciences' },
  { code:'PHIL 3030', name:'Ethics and Technology',                         faculty:'Arts & Social Sciences' },
  { code:'PHIL 4010', name:'Metaphysics',                                   faculty:'Arts & Social Sciences' },
  { code:'PHIL 4020', name:'Advanced Ethics',                               faculty:'Arts & Social Sciences' },
  // Political Science
  { code:'POLI 1000', name:'Introduction to Political Science',             faculty:'Arts & Social Sciences' },
  { code:'POLI 1500', name:'Introduction to International Relations',       faculty:'Arts & Social Sciences' },
  { code:'POLI 2000', name:'Canadian Government and Politics',              faculty:'Arts & Social Sciences' },
  { code:'POLI 2200', name:'Comparative Politics',                          faculty:'Arts & Social Sciences' },
  { code:'POLI 2500', name:'International Relations Theory',                faculty:'Arts & Social Sciences' },
  { code:'POLI 3000', name:'Political Theory',                              faculty:'Arts & Social Sciences' },
  { code:'POLI 3100', name:'Canadian Public Policy',                        faculty:'Arts & Social Sciences' },
  { code:'POLI 3200', name:'Global Governance',                             faculty:'Arts & Social Sciences' },
  { code:'POLI 3300', name:'Politics of Developing Countries',              faculty:'Arts & Social Sciences' },
  { code:'POLI 4000', name:'Advanced Political Theory',                     faculty:'Arts & Social Sciences' },
  { code:'POLI 4100', name:'Foreign Policy Analysis',                       faculty:'Arts & Social Sciences' },
  // Psychology
  { code:'PSYC 1011', name:'Introductory Psychology I',                     faculty:'Arts & Social Sciences' },
  { code:'PSYC 1012', name:'Introductory Psychology II',                    faculty:'Arts & Social Sciences' },
  { code:'PSYC 2000', name:'Research Methods in Psychology',                faculty:'Arts & Social Sciences' },
  { code:'PSYC 2012', name:'Developmental Psychology',                      faculty:'Arts & Social Sciences' },
  { code:'PSYC 2021', name:'Social Psychology',                             faculty:'Arts & Social Sciences' },
  { code:'PSYC 2022', name:'Abnormal Psychology',                           faculty:'Arts & Social Sciences' },
  { code:'PSYC 2030', name:'Biological Psychology',                         faculty:'Arts & Social Sciences' },
  { code:'PSYC 2060', name:'Cognitive Psychology',                          faculty:'Arts & Social Sciences' },
  { code:'PSYC 3000', name:'Advanced Research Methods',                     faculty:'Arts & Social Sciences' },
  { code:'PSYC 3012', name:'Child Psychopathology',                         faculty:'Arts & Social Sciences' },
  { code:'PSYC 3021', name:'Health Psychology',                             faculty:'Arts & Social Sciences' },
  { code:'PSYC 3030', name:'Personality Psychology',                        faculty:'Arts & Social Sciences' },
  { code:'PSYC 3060', name:'Perception',                                    faculty:'Arts & Social Sciences' },
  { code:'PSYC 4021', name:'Clinical Psychology',                           faculty:'Arts & Social Sciences' },
  { code:'PSYC 4030', name:'Neuropsychology',                               faculty:'Arts & Social Sciences' },
  { code:'PSYC 4060', name:'Advanced Cognitive Neuroscience',               faculty:'Arts & Social Sciences' },
  // Sociology & Social Anthropology
  { code:'SOSA 1000', name:'Introductory Sociology',                        faculty:'Arts & Social Sciences' },
  { code:'SOSA 1002', name:'Introductory Social Anthropology',              faculty:'Arts & Social Sciences' },
  { code:'SOSA 2000', name:'Sociological Theory',                           faculty:'Arts & Social Sciences' },
  { code:'SOSA 2100', name:'Research Methods in Sociology',                 faculty:'Arts & Social Sciences' },
  { code:'SOSA 2200', name:'Gender and Society',                            faculty:'Arts & Social Sciences' },
  { code:'SOSA 2300', name:'Sociology of Work',                             faculty:'Arts & Social Sciences' },
  { code:'SOSA 3000', name:'Advanced Sociological Theory',                  faculty:'Arts & Social Sciences' },
  { code:'SOSA 3100', name:'Race, Ethnicity and Society',                   faculty:'Arts & Social Sciences' },
  { code:'SOSA 3200', name:'Sociology of Health and Illness',               faculty:'Arts & Social Sciences' },
  { code:'SOSA 3300', name:'Social Stratification',                         faculty:'Arts & Social Sciences' },
  { code:'SOSA 4000', name:'Qualitative Research Methods',                  faculty:'Arts & Social Sciences' },
  { code:'SOSA 4100', name:'Globalization and Society',                     faculty:'Arts & Social Sciences' },
  // Theatre
  { code:'THEA 1000', name:'Introduction to Theatre',                       faculty:'Arts & Social Sciences' },
  { code:'THEA 2000', name:'Acting I',                                      faculty:'Arts & Social Sciences' },
  { code:'THEA 2001', name:'Theatre History',                               faculty:'Arts & Social Sciences' },
  { code:'THEA 3000', name:'Directing',                                     faculty:'Arts & Social Sciences' },
  { code:'THEA 4000', name:'Advanced Performance',                          faculty:'Arts & Social Sciences' },

  // ══════════════════════════════════════════
  // FACULTY OF COMPUTER SCIENCE
  // ══════════════════════════════════════════
  { code:'CSCI 1100', name:'Society, Ethics and Technology',                faculty:'Computer Science' },
  { code:'CSCI 1101', name:'Introduction to Computer Science',              faculty:'Computer Science' },
  { code:'CSCI 1105', name:'Introductory Programming',                      faculty:'Computer Science' },
  { code:'CSCI 1110', name:'Introduction to Programming in Python',         faculty:'Computer Science' },
  { code:'CSCI 1120', name:'Introduction to Computing Systems',             faculty:'Computer Science' },
  { code:'CSCI 2110', name:'Data Structures and Algorithms',                faculty:'Computer Science' },
  { code:'CSCI 2112', name:'Discrete Mathematics for Computer Science',     faculty:'Computer Science' },
  { code:'CSCI 2115', name:'Theory of Computing',                           faculty:'Computer Science' },
  { code:'CSCI 2121', name:'Computer Organization and Assembly Language',   faculty:'Computer Science' },
  { code:'CSCI 2122', name:'Systems Programming',                           faculty:'Computer Science' },
  { code:'CSCI 2130', name:'Intermediate Programming in C++',               faculty:'Computer Science' },
  { code:'CSCI 2141', name:'Intro to Database Systems',                     faculty:'Computer Science' },
  { code:'CSCI 3101', name:'Social and Professional Issues in CS',          faculty:'Computer Science' },
  { code:'CSCI 3110', name:'Algorithms',                                    faculty:'Computer Science' },
  { code:'CSCI 3120', name:'Operating Systems',                             faculty:'Computer Science' },
  { code:'CSCI 3130', name:'Software Development',                          faculty:'Computer Science' },
  { code:'CSCI 3132', name:'Object-Oriented Design and Development',        faculty:'Computer Science' },
  { code:'CSCI 3141', name:'Principles of Database Systems',                faculty:'Computer Science' },
  { code:'CSCI 3151', name:'Foundations of Machine Learning',               faculty:'Computer Science' },
  { code:'CSCI 3161', name:'Introduction to Computer Graphics',             faculty:'Computer Science' },
  { code:'CSCI 3171', name:'Network Computing',                             faculty:'Computer Science' },
  { code:'CSCI 3172', name:'Web-Centric Computing',                         faculty:'Computer Science' },
  { code:'CSCI 4110', name:'Advanced Algorithms',                           faculty:'Computer Science' },
  { code:'CSCI 4116', name:'Cryptography',                                  faculty:'Computer Science' },
  { code:'CSCI 4120', name:'Computer Architecture',                         faculty:'Computer Science' },
  { code:'CSCI 4130', name:'Compiler Construction',                         faculty:'Computer Science' },
  { code:'CSCI 4141', name:'Advanced Database Systems',                     faculty:'Computer Science' },
  { code:'CSCI 4150', name:'Artificial Intelligence',                       faculty:'Computer Science' },
  { code:'CSCI 4152', name:'Natural Language Processing',                   faculty:'Computer Science' },
  { code:'CSCI 4154', name:'Information Retrieval',                         faculty:'Computer Science' },
  { code:'CSCI 4160', name:'Computer Vision',                               faculty:'Computer Science' },
  { code:'CSCI 4170', name:'Advanced Computer Networks',                    faculty:'Computer Science' },
  { code:'CSCI 4176', name:'Mobile Computing',                              faculty:'Computer Science' },
  { code:'CSCI 4177', name:'Advanced Web Services',                         faculty:'Computer Science' },
  { code:'CSCI 4181', name:'Computer Security',                             faculty:'Computer Science' },
  { code:'CSCI 4192', name:'Human-Computer Interaction',                    faculty:'Computer Science' },

  // ══════════════════════════════════════════
  // FACULTY OF DENTISTRY
  // ══════════════════════════════════════════
  { code:'DENT 1001', name:'Oral Biology I',                                faculty:'Dentistry' },
  { code:'DENT 1002', name:'Oral Biology II',                               faculty:'Dentistry' },
  { code:'DENT 2001', name:'Dental Anatomy and Histology',                  faculty:'Dentistry' },
  { code:'DENT 2002', name:'Oral Pathology',                                faculty:'Dentistry' },
  { code:'DENT 3001', name:'Periodontology',                                faculty:'Dentistry' },
  { code:'DENT 3002', name:'Operative Dentistry',                           faculty:'Dentistry' },
  { code:'DENT 3003', name:'Prosthodontics I',                              faculty:'Dentistry' },
  { code:'DENT 3004', name:'Endodontics',                                   faculty:'Dentistry' },
  { code:'DENT 4001', name:'Oral Surgery',                                  faculty:'Dentistry' },
  { code:'DENT 4002', name:'Prosthodontics II',                             faculty:'Dentistry' },
  { code:'DENT 4003', name:'Pediatric Dentistry',                           faculty:'Dentistry' },
  { code:'DENT 4004', name:'Orthodontics',                                  faculty:'Dentistry' },
  { code:'DHYG 1001', name:'Introduction to Dental Hygiene',               faculty:'Dentistry' },
  { code:'DHYG 2001', name:'Dental Hygiene Theory I',                      faculty:'Dentistry' },
  { code:'DHYG 3001', name:'Dental Hygiene Clinic I',                      faculty:'Dentistry' },
  { code:'DHYG 4001', name:'Community Oral Health',                        faculty:'Dentistry' },

  // ══════════════════════════════════════════
  // FACULTY OF ENGINEERING
  // ══════════════════════════════════════════
  { code:'ENGI 1100', name:'Engineering Design and Communication',          faculty:'Engineering' },
  { code:'ENGI 1101', name:'Engineering Mechanics I: Statics',              faculty:'Engineering' },
  { code:'ENGI 1102', name:'Engineering Mechanics II: Dynamics',            faculty:'Engineering' },
  { code:'ENGI 2100', name:'Thermodynamics I',                              faculty:'Engineering' },
  { code:'ENGI 2101', name:'Fluid Mechanics',                               faculty:'Engineering' },
  { code:'ENGI 3100', name:'Engineering Mathematics',                       faculty:'Engineering' },
  { code:'CHEE 2001', name:'Chemical Process Principles',                   faculty:'Engineering' },
  { code:'CHEE 2002', name:'Thermodynamics for Chemical Engineers',         faculty:'Engineering' },
  { code:'CHEE 3001', name:'Chemical Reaction Engineering',                 faculty:'Engineering' },
  { code:'CHEE 3002', name:'Mass Transfer Operations',                      faculty:'Engineering' },
  { code:'CHEE 3003', name:'Process Control',                               faculty:'Engineering' },
  { code:'CHEE 4001', name:'Chemical Plant Design',                         faculty:'Engineering' },
  { code:'CHEE 4002', name:'Polymer Engineering',                           faculty:'Engineering' },
  { code:'CIVL 2001', name:'Surveying',                                     faculty:'Engineering' },
  { code:'CIVL 2002', name:'Mechanics of Materials',                        faculty:'Engineering' },
  { code:'CIVL 3001', name:'Structural Analysis',                           faculty:'Engineering' },
  { code:'CIVL 3002', name:'Geotechnical Engineering',                      faculty:'Engineering' },
  { code:'CIVL 3003', name:'Transportation Engineering',                    faculty:'Engineering' },
  { code:'CIVL 3004', name:'Hydraulics',                                    faculty:'Engineering' },
  { code:'CIVL 4001', name:'Reinforced Concrete Design',                    faculty:'Engineering' },
  { code:'CIVL 4002', name:'Steel Structure Design',                        faculty:'Engineering' },
  { code:'CIVL 4003', name:'Environmental Engineering',                     faculty:'Engineering' },
  { code:'ECED 2200', name:'Circuit Theory',                                faculty:'Engineering' },
  { code:'ECED 2210', name:'Digital Circuits and Systems',                  faculty:'Engineering' },
  { code:'ECED 3200', name:'Electronics I',                                 faculty:'Engineering' },
  { code:'ECED 3210', name:'Electronics II',                                faculty:'Engineering' },
  { code:'ECED 3300', name:'Signals and Systems',                           faculty:'Engineering' },
  { code:'ECED 3400', name:'Electromagnetic Fields',                        faculty:'Engineering' },
  { code:'ECED 3600', name:'Embedded Systems',                              faculty:'Engineering' },
  { code:'ECED 4200', name:'VLSI Design',                                   faculty:'Engineering' },
  { code:'ECED 4300', name:'Communications Engineering',                    faculty:'Engineering' },
  { code:'ECED 4400', name:'Control Systems',                               faculty:'Engineering' },
  { code:'ECED 4600', name:'Computer Architecture',                         faculty:'Engineering' },
  { code:'IENG 2001', name:'Engineering Statistics',                        faculty:'Engineering' },
  { code:'IENG 3001', name:'Operations Research',                           faculty:'Engineering' },
  { code:'IENG 3002', name:'Production and Operations Management',          faculty:'Engineering' },
  { code:'IENG 4001', name:'Engineering Project Management',                faculty:'Engineering' },
  { code:'MECH 2001', name:'Machine Design I',                              faculty:'Engineering' },
  { code:'MECH 2002', name:'Manufacturing Processes',                       faculty:'Engineering' },
  { code:'MECH 3001', name:'Heat Transfer',                                 faculty:'Engineering' },
  { code:'MECH 3002', name:'Machine Design II',                             faculty:'Engineering' },
  { code:'MECH 3003', name:'Vibrations',                                    faculty:'Engineering' },
  { code:'MECH 4001', name:'Finite Element Analysis',                       faculty:'Engineering' },
  { code:'MECH 4002', name:'Computational Fluid Dynamics',                  faculty:'Engineering' },
  { code:'MINE 2001', name:'Mining Engineering Fundamentals',               faculty:'Engineering' },
  { code:'MINE 3001', name:'Rock Mechanics',                                faculty:'Engineering' },
  { code:'MINE 4001', name:'Mine Design',                                   faculty:'Engineering' },
  { code:'MREN 2001', name:'Materials Science',                             faculty:'Engineering' },
  { code:'MREN 3001', name:'Corrosion Engineering',                         faculty:'Engineering' },
  { code:'MREN 4001', name:'Advanced Materials',                            faculty:'Engineering' },

  // ══════════════════════════════════════════
  // FACULTY OF HEALTH
  // ══════════════════════════════════════════
  { code:'HESA 2001', name:'Introduction to Health Administration',         faculty:'Health' },
  { code:'HESA 3001', name:'Health Care Systems',                           faculty:'Health' },
  { code:'HESA 3002', name:'Health Policy and Politics',                    faculty:'Health' },
  { code:'HESA 4001', name:'Strategic Management in Health',                faculty:'Health' },
  { code:'HPRO 1000', name:'Introduction to Health',                       faculty:'Health' },
  { code:'HPRO 2000', name:'Epidemiology',                                  faculty:'Health' },
  { code:'HPRO 2001', name:'Health Behaviour',                              faculty:'Health' },
  { code:'HPRO 3000', name:'Global Health',                                 faculty:'Health' },
  { code:'HPRO 3100', name:'Health Policy',                                 faculty:'Health' },
  { code:'HPRO 4000', name:'Community Health Programming',                  faculty:'Health' },
  { code:'KINE 1000', name:'Introduction to Kinesiology',                   faculty:'Health' },
  { code:'KINE 1401', name:'Human Anatomy I',                               faculty:'Health' },
  { code:'KINE 1402', name:'Human Anatomy II',                              faculty:'Health' },
  { code:'KINE 2200', name:'Exercise Physiology I',                         faculty:'Health' },
  { code:'KINE 2300', name:'Biomechanics',                                  faculty:'Health' },
  { code:'KINE 2400', name:'Motor Learning and Control',                    faculty:'Health' },
  { code:'KINE 3200', name:'Advanced Exercise Physiology',                  faculty:'Health' },
  { code:'KINE 3300', name:'Sport Psychology',                              faculty:'Health' },
  { code:'KINE 3400', name:'Measurement and Evaluation',                    faculty:'Health' },
  { code:'KINE 4200', name:'Clinical Exercise Physiology',                  faculty:'Health' },
  { code:'KINE 4300', name:'Strength and Conditioning',                     faculty:'Health' },
  { code:'NURS 1000', name:'Introduction to Nursing Practice',              faculty:'Health' },
  { code:'NURS 2000', name:'Health Assessment',                             faculty:'Health' },
  { code:'NURS 2001', name:'Pathophysiology for Nurses',                    faculty:'Health' },
  { code:'NURS 3000', name:'Adult Health Nursing',                          faculty:'Health' },
  { code:'NURS 3001', name:'Maternal and Child Nursing',                    faculty:'Health' },
  { code:'NURS 3002', name:'Mental Health Nursing',                         faculty:'Health' },
  { code:'NURS 4000', name:'Community Health Nursing',                      faculty:'Health' },
  { code:'NURS 4001', name:'Nursing Leadership and Management',             faculty:'Health' },
  { code:'OCCU 2001', name:'Foundations of Occupational Therapy',           faculty:'Health' },
  { code:'OCCU 3001', name:'Occupational Therapy Practice I',               faculty:'Health' },
  { code:'OCCU 4001', name:'Occupational Therapy Practice II',              faculty:'Health' },
  { code:'PHYT 2001', name:'Foundations of Physiotherapy',                  faculty:'Health' },
  { code:'PHYT 3001', name:'Musculoskeletal Physiotherapy',                 faculty:'Health' },
  { code:'PHYT 4001', name:'Neurological Physiotherapy',                    faculty:'Health' },
  { code:'RECR 2001', name:'Introduction to Recreation Management',         faculty:'Health' },
  { code:'RECR 3001', name:'Recreation Programming',                        faculty:'Health' },
  { code:'SLWK 2001', name:'Introduction to Social Work',                   faculty:'Health' },
  { code:'SLWK 3001', name:'Social Work Practice I',                        faculty:'Health' },
  { code:'SLWK 4001', name:'Social Work Practice II',                       faculty:'Health' },

  // ══════════════════════════════════════════
  // FACULTY OF LAW
  // ══════════════════════════════════════════
  { code:'LAWS 1000', name:'Legal Systems and Methods',                     faculty:'Law' },
  { code:'LAWS 1001', name:'Contracts',                                     faculty:'Law' },
  { code:'LAWS 1002', name:'Torts',                                         faculty:'Law' },
  { code:'LAWS 1003', name:'Property Law',                                  faculty:'Law' },
  { code:'LAWS 1004', name:'Constitutional Law I',                          faculty:'Law' },
  { code:'LAWS 2000', name:'Constitutional Law II',                         faculty:'Law' },
  { code:'LAWS 2001', name:'Criminal Law',                                  faculty:'Law' },
  { code:'LAWS 2002', name:'Administrative Law',                            faculty:'Law' },
  { code:'LAWS 2003', name:'Evidence',                                      faculty:'Law' },
  { code:'LAWS 2004', name:'Equity and Trusts',                             faculty:'Law' },
  { code:'LAWS 3000', name:'Corporate Law',                                 faculty:'Law' },
  { code:'LAWS 3001', name:'International Law',                             faculty:'Law' },
  { code:'LAWS 3002', name:'Family Law',                                    faculty:'Law' },
  { code:'LAWS 3003', name:'Labour Law',                                    faculty:'Law' },
  { code:'LAWS 3004', name:'Tax Law',                                       faculty:'Law' },
  { code:'LAWS 4000', name:'Environmental Law',                             faculty:'Law' },
  { code:'LAWS 4001', name:'Intellectual Property Law',                     faculty:'Law' },
  { code:'LAWS 4002', name:'Immigration Law',                               faculty:'Law' },
  { code:'LAWS 4003', name:'Human Rights Law',                              faculty:'Law' },
  { code:'LAWS 4004', name:'Indigenous Law',                                faculty:'Law' },

  // ══════════════════════════════════════════
  // FACULTY OF MANAGEMENT
  // ══════════════════════════════════════════
  // Commerce
  { code:'COMM 1001', name:'Introduction to Business',                      faculty:'Management' },
  { code:'COMM 2201', name:'Organizational Behaviour',                      faculty:'Management' },
  { code:'COMM 2301', name:'Marketing Principles',                          faculty:'Management' },
  { code:'COMM 2401', name:'Financial Accounting',                          faculty:'Management' },
  { code:'COMM 2402', name:'Managerial Accounting',                         faculty:'Management' },
  { code:'COMM 2501', name:'Business Statistics',                           faculty:'Management' },
  { code:'COMM 2601', name:'Business Law',                                  faculty:'Management' },
  { code:'COMM 3301', name:'Consumer Behaviour',                            faculty:'Management' },
  { code:'COMM 3302', name:'Digital Marketing',                             faculty:'Management' },
  { code:'COMM 3303', name:'Marketing Research',                            faculty:'Management' },
  { code:'COMM 3401', name:'Intermediate Financial Accounting I',           faculty:'Management' },
  { code:'COMM 3402', name:'Intermediate Financial Accounting II',          faculty:'Management' },
  { code:'COMM 3403', name:'Cost Accounting',                               faculty:'Management' },
  { code:'COMM 3501', name:'Operations Management',                         faculty:'Management' },
  { code:'COMM 3601', name:'Corporate Finance',                             faculty:'Management' },
  { code:'COMM 3602', name:'Investment Analysis',                           faculty:'Management' },
  { code:'COMM 3701', name:'Human Resource Management',                     faculty:'Management' },
  { code:'COMM 4201', name:'Strategic Management',                          faculty:'Management' },
  { code:'COMM 4202', name:'Business Ethics',                               faculty:'Management' },
  { code:'COMM 4301', name:'International Marketing',                       faculty:'Management' },
  { code:'COMM 4401', name:'Advanced Accounting',                           faculty:'Management' },
  { code:'COMM 4601', name:'Financial Derivatives',                         faculty:'Management' },
  { code:'COMM 4701', name:'Entrepreneurship',                              faculty:'Management' },
  { code:'COMM 4801', name:'Supply Chain Management',                       faculty:'Management' },
  // Management
  { code:'MGMT 1101', name:'Introduction to Management',                    faculty:'Management' },
  { code:'MGMT 2202', name:'Organizational Theory',                         faculty:'Management' },
  { code:'MGMT 3301', name:'Strategic Management',                          faculty:'Management' },
  { code:'MGMT 4401', name:'Leadership and Change Management',              faculty:'Management' },
  // Information Management
  { code:'INFO 2000', name:'Foundations of Information Management',         faculty:'Management' },
  { code:'INFO 2001', name:'Introduction to Data Management',               faculty:'Management' },
  { code:'INFO 3000', name:'Information Architecture',                      faculty:'Management' },
  { code:'INFO 3001', name:'Database Design and Management',                faculty:'Management' },
  { code:'INFO 3100', name:'Digital Libraries',                             faculty:'Management' },
  { code:'INFO 3200', name:'Knowledge Organization',                        faculty:'Management' },
  { code:'INFO 4000', name:'Knowledge Management',                          faculty:'Management' },
  { code:'INFO 4100', name:'Research Methods in Information Studies',       faculty:'Management' },
  // Library & Information Studies
  { code:'LIBS 2001', name:'Introduction to Library Science',               faculty:'Management' },
  { code:'LIBS 3001', name:'Reference and Information Services',            faculty:'Management' },
  { code:'LIBS 4001', name:'Collection Development',                        faculty:'Management' },
  // Public Administration
  { code:'PUAD 2001', name:'Introduction to Public Administration',         faculty:'Management' },
  { code:'PUAD 3001', name:'Public Policy Analysis',                        faculty:'Management' },
  { code:'PUAD 4001', name:'Public Sector Management',                      faculty:'Management' },

  // ══════════════════════════════════════════
  // FACULTY OF MEDICINE
  // ══════════════════════════════════════════
  { code:'ANAT 2001', name:'Gross Anatomy',                                 faculty:'Medicine' },
  { code:'ANAT 3001', name:'Neuroanatomy',                                  faculty:'Medicine' },
  { code:'ANAT 4001', name:'Advanced Human Anatomy',                        faculty:'Medicine' },
  { code:'BIOC 2001', name:'Biochemistry I: Macromolecules',                faculty:'Medicine' },
  { code:'BIOC 2002', name:'Biochemistry II: Metabolism',                   faculty:'Medicine' },
  { code:'BIOC 3001', name:'Molecular Biology',                             faculty:'Medicine' },
  { code:'BIOC 4001', name:'Advanced Biochemistry',                         faculty:'Medicine' },
  { code:'MICI 2001', name:'General Microbiology',                          faculty:'Medicine' },
  { code:'MICI 3001', name:'Medical Microbiology',                          faculty:'Medicine' },
  { code:'MICI 3002', name:'Immunology',                                    faculty:'Medicine' },
  { code:'MICI 4001', name:'Virology',                                      faculty:'Medicine' },
  { code:'PHAR 2001', name:'Introduction to Pharmacology',                  faculty:'Medicine' },
  { code:'PHAR 3001', name:'Pharmacology I: Autonomic and Cardiovascular',  faculty:'Medicine' },
  { code:'PHAR 4001', name:'Clinical Pharmacology',                         faculty:'Medicine' },
  { code:'PATH 2001', name:'General Pathology',                             faculty:'Medicine' },
  { code:'PATH 3001', name:'Systemic Pathology',                            faculty:'Medicine' },
  { code:'PHYL 2001', name:'Human Physiology I',                            faculty:'Medicine' },
  { code:'PHYL 2002', name:'Human Physiology II',                           faculty:'Medicine' },
  { code:'PHYL 3001', name:'Cardiovascular Physiology',                     faculty:'Medicine' },
  { code:'PHYL 4001', name:'Advanced Physiology',                           faculty:'Medicine' },

  // ══════════════════════════════════════════
  // FACULTY OF SCIENCE
  // ══════════════════════════════════════════
  // Biology
  { code:'BIOL 1010', name:'Introduction to Biology: Cells and Genetics',   faculty:'Science' },
  { code:'BIOL 1011', name:'Introduction to Biology: Diversity and Ecology',faculty:'Science' },
  { code:'BIOL 2020', name:'Cell Biology',                                  faculty:'Science' },
  { code:'BIOL 2030', name:'Genetics',                                      faculty:'Science' },
  { code:'BIOL 2040', name:'Ecology',                                       faculty:'Science' },
  { code:'BIOL 2060', name:'Molecular Biology',                             faculty:'Science' },
  { code:'BIOL 2080', name:'Comparative Animal Physiology',                 faculty:'Science' },
  { code:'BIOL 2090', name:'Plant Biology',                                 faculty:'Science' },
  { code:'BIOL 3010', name:'Biochemistry for Biologists',                   faculty:'Science' },
  { code:'BIOL 3030', name:'Microbiology',                                  faculty:'Science' },
  { code:'BIOL 3060', name:'Evolutionary Biology',                          faculty:'Science' },
  { code:'BIOL 3090', name:'Marine Biology',                                faculty:'Science' },
  { code:'BIOL 3120', name:'Bioinformatics',                                faculty:'Science' },
  { code:'BIOL 3150', name:'Developmental Biology',                         faculty:'Science' },
  { code:'BIOL 4010', name:'Genomics and Proteomics',                       faculty:'Science' },
  { code:'BIOL 4060', name:'Conservation Biology',                          faculty:'Science' },
  { code:'BIOL 4090', name:'Neurobiology',                                  faculty:'Science' },
  // Chemistry
  { code:'CHEM 1011', name:'General Chemistry I',                           faculty:'Science' },
  { code:'CHEM 1012', name:'General Chemistry II',                          faculty:'Science' },
  { code:'CHEM 2001', name:'Analytical Chemistry',                          faculty:'Science' },
  { code:'CHEM 2003', name:'Organic Chemistry I',                           faculty:'Science' },
  { code:'CHEM 2004', name:'Organic Chemistry II',                          faculty:'Science' },
  { code:'CHEM 2401', name:'Physical Chemistry I',                          faculty:'Science' },
  { code:'CHEM 2402', name:'Physical Chemistry II',                         faculty:'Science' },
  { code:'CHEM 3400', name:'Inorganic Chemistry',                           faculty:'Science' },
  { code:'CHEM 3401', name:'Advanced Organic Chemistry',                    faculty:'Science' },
  { code:'CHEM 3402', name:'Spectroscopy',                                  faculty:'Science' },
  { code:'CHEM 4001', name:'Biochemistry I',                                faculty:'Science' },
  { code:'CHEM 4002', name:'Biochemistry II',                               faculty:'Science' },
  { code:'CHEM 4100', name:'Computational Chemistry',                       faculty:'Science' },
  // Earth Sciences
  { code:'ERTH 1080', name:'Introduction to Earth Science',                 faculty:'Science' },
  { code:'ERTH 2001', name:'Mineralogy',                                    faculty:'Science' },
  { code:'ERTH 2002', name:'Petrology',                                     faculty:'Science' },
  { code:'ERTH 3001', name:'Structural Geology',                            faculty:'Science' },
  { code:'ERTH 3002', name:'Sedimentology',                                 faculty:'Science' },
  { code:'ERTH 4001', name:'Geophysics',                                    faculty:'Science' },
  // Environmental Science
  { code:'ENVS 1000', name:'Introduction to Environmental Science',         faculty:'Science' },
  { code:'ENVS 2000', name:'Environmental Assessment',                      faculty:'Science' },
  { code:'ENVS 3000', name:'Climate Change Science',                        faculty:'Science' },
  { code:'ENVS 3100', name:'Pollution and Remediation',                     faculty:'Science' },
  { code:'ENVS 4000', name:'Environmental Policy and Management',           faculty:'Science' },
  // Mathematics
  { code:'MATH 1000', name:'Differential Calculus',                         faculty:'Science' },
  { code:'MATH 1010', name:'Integral Calculus',                             faculty:'Science' },
  { code:'MATH 1030', name:'Business Mathematics I',                        faculty:'Science' },
  { code:'MATH 1060', name:'Precalculus Mathematics',                       faculty:'Science' },
  { code:'MATH 1115', name:'Mathematics for Life Sciences',                 faculty:'Science' },
  { code:'MATH 2001', name:'Intermediate Calculus I',                       faculty:'Science' },
  { code:'MATH 2002', name:'Intermediate Calculus II',                      faculty:'Science' },
  { code:'MATH 2030', name:'Business Mathematics II',                       faculty:'Science' },
  { code:'MATH 2040', name:'Mathematics for Engineering',                   faculty:'Science' },
  { code:'MATH 2060', name:'Introduction to Analysis',                      faculty:'Science' },
  { code:'MATH 2101', name:'Linear Algebra I',                              faculty:'Science' },
  { code:'MATH 2112', name:'Discrete Mathematics',                          faculty:'Science' },
  { code:'MATH 2135', name:'Linear Algebra II',                             faculty:'Science' },
  { code:'MATH 3000', name:'Real Analysis',                                 faculty:'Science' },
  { code:'MATH 3030', name:'Differential Equations',                        faculty:'Science' },
  { code:'MATH 3070', name:'Partial Differential Equations',                faculty:'Science' },
  { code:'MATH 3110', name:'Algebra I: Groups and Rings',                   faculty:'Science' },
  { code:'MATH 3210', name:'Complex Variables',                             faculty:'Science' },
  { code:'MATH 3250', name:'Introduction to Number Theory',                 faculty:'Science' },
  { code:'MATH 3360', name:'Mathematical Modelling',                        faculty:'Science' },
  { code:'MATH 4000', name:'Measure Theory and Integration',                faculty:'Science' },
  { code:'MATH 4030', name:'Advanced Differential Equations',               faculty:'Science' },
  // Neuroscience
  { code:'NESC 2470', name:'Introduction to Neuroscience',                  faculty:'Science' },
  { code:'NESC 3470', name:'Systems Neuroscience',                          faculty:'Science' },
  { code:'NESC 3480', name:'Cellular and Molecular Neuroscience',           faculty:'Science' },
  { code:'NESC 4470', name:'Neuropharmacology',                             faculty:'Science' },
  { code:'NESC 4480', name:'Neuroscience Research Methods',                 faculty:'Science' },
  // Oceanography
  { code:'OCEA 2000', name:'Introduction to Oceanography',                  faculty:'Science' },
  { code:'OCEA 3000', name:'Physical Oceanography',                         faculty:'Science' },
  { code:'OCEA 3100', name:'Chemical Oceanography',                         faculty:'Science' },
  { code:'OCEA 3200', name:'Geological Oceanography',                       faculty:'Science' },
  { code:'OCEA 4000', name:'Biological Oceanography',                       faculty:'Science' },
  { code:'OCEA 4100', name:'Ocean Climate',                                 faculty:'Science' },
  // Physics
  { code:'PHYS 1100', name:'Introductory Physics I: Mechanics',             faculty:'Science' },
  { code:'PHYS 1101', name:'Introductory Physics II: Electricity & Magnetism',faculty:'Science' },
  { code:'PHYS 1300', name:'Physics for Life Sciences I',                   faculty:'Science' },
  { code:'PHYS 1301', name:'Physics for Life Sciences II',                  faculty:'Science' },
  { code:'PHYS 2000', name:'Modern Physics',                                faculty:'Science' },
  { code:'PHYS 2005', name:'Classical Mechanics',                           faculty:'Science' },
  { code:'PHYS 2010', name:'Electricity and Magnetism',                     faculty:'Science' },
  { code:'PHYS 3000', name:'Quantum Mechanics I',                           faculty:'Science' },
  { code:'PHYS 3001', name:'Quantum Mechanics II',                          faculty:'Science' },
  { code:'PHYS 3010', name:'Thermodynamics and Statistical Mechanics',      faculty:'Science' },
  { code:'PHYS 3020', name:'Atmospheric Science',                           faculty:'Science' },
  { code:'PHYS 4000', name:'Condensed Matter Physics',                      faculty:'Science' },
  { code:'PHYS 4010', name:'Nuclear and Particle Physics',                  faculty:'Science' },
  // Statistics
  { code:'STAT 1060', name:'Introduction to Statistics I',                  faculty:'Science' },
  { code:'STAT 1061', name:'Introduction to Statistics II',                 faculty:'Science' },
  { code:'STAT 2060', name:'Introduction to Probability and Statistics',    faculty:'Science' },
  { code:'STAT 2080', name:'Statistics for Scientists and Engineers',       faculty:'Science' },
  { code:'STAT 3460', name:'Probability I',                                 faculty:'Science' },
  { code:'STAT 3461', name:'Probability II',                                faculty:'Science' },
  { code:'STAT 3470', name:'Regression Analysis',                           faculty:'Science' },
  { code:'STAT 3480', name:'Design of Experiments',                         faculty:'Science' },
  { code:'STAT 4060', name:'Mathematical Statistics I',                     faculty:'Science' },
  { code:'STAT 4061', name:'Mathematical Statistics II',                    faculty:'Science' },
  { code:'STAT 4200', name:'Applied Multivariate Analysis',                 faculty:'Science' },
];
