// Dalhousie University Course Database
const DAL_COURSES = [
  // ===== COMPUTER SCIENCE =====
  { code: 'CSCI 1100', name: 'Society, Ethics and Technology' },
  { code: 'CSCI 1101', name: 'Introduction to Computer Science' },
  { code: 'CSCI 1105', name: 'Introductory Programming' },
  { code: 'CSCI 1110', name: 'Introduction to Programming' },
  { code: 'CSCI 1120', name: 'Introduction to Computing Systems' },
  { code: 'CSCI 2110', name: 'Data Structures and Algorithms' },
  { code: 'CSCI 2112', name: 'Discrete Mathematics for Computer Science' },
  { code: 'CSCI 2115', name: 'Theory of Computing' },
  { code: 'CSCI 2121', name: 'Computer Organization and Assembly' },
  { code: 'CSCI 2122', name: 'Systems Programming' },
  { code: 'CSCI 2130', name: 'Intermediate Programming' },
  { code: 'CSCI 2141', name: 'Intro to Database Systems' },
  { code: 'CSCI 3101', name: 'Social and Professional Issues in CS' },
  { code: 'CSCI 3110', name: 'Algorithms' },
  { code: 'CSCI 3120', name: 'Operating Systems' },
  { code: 'CSCI 3130', name: 'Software Development' },
  { code: 'CSCI 3132', name: 'Object-Oriented Design and Development' },
  { code: 'CSCI 3141', name: 'Principles of Database Systems' },
  { code: 'CSCI 3151', name: 'Foundations of Machine Learning' },
  { code: 'CSCI 3161', name: 'Introduction to Computer Graphics' },
  { code: 'CSCI 3171', name: 'Network Computing' },
  { code: 'CSCI 3172', name: 'Web-Centric Computing' },
  { code: 'CSCI 4110', name: 'Advanced Algorithms' },
  { code: 'CSCI 4116', name: 'Cryptography' },
  { code: 'CSCI 4120', name: 'Computer Architecture' },
  { code: 'CSCI 4130', name: 'Compiler Construction' },
  { code: 'CSCI 4141', name: 'Advanced Database Systems' },
  { code: 'CSCI 4150', name: 'Artificial Intelligence' },
  { code: 'CSCI 4152', name: 'Natural Language Processing' },
  { code: 'CSCI 4154', name: 'Information Retrieval' },
  { code: 'CSCI 4160', name: 'Computer Vision' },
  { code: 'CSCI 4170', name: 'Advanced Computer Networks' },
  { code: 'CSCI 4176', name: 'Mobile Computing' },
  { code: 'CSCI 4177', name: 'Advanced Web Services' },
  { code: 'CSCI 4181', name: 'Computer Security' },
  { code: 'CSCI 4192', name: 'Human-Computer Interaction' },

  // ===== MATHEMATICS =====
  { code: 'MATH 1000', name: 'Differential Calculus' },
  { code: 'MATH 1010', name: 'Integral Calculus' },
  { code: 'MATH 1030', name: 'Business Mathematics I' },
  { code: 'MATH 1060', name: 'Precalculus Mathematics' },
  { code: 'MATH 1115', name: 'Mathematics for Life Sciences' },
  { code: 'MATH 1215', name: 'Applied Calculus for Life Scientists' },
  { code: 'MATH 2001', name: 'Intermediate Calculus I' },
  { code: 'MATH 2002', name: 'Intermediate Calculus II' },
  { code: 'MATH 2030', name: 'Business Mathematics II' },
  { code: 'MATH 2040', name: 'Mathematics for Engineering' },
  { code: 'MATH 2060', name: 'Introduction to Analysis' },
  { code: 'MATH 2101', name: 'Linear Algebra I' },
  { code: 'MATH 2112', name: 'Discrete Mathematics' },
  { code: 'MATH 2120', name: 'Abstract Algebra' },
  { code: 'MATH 2135', name: 'Linear Algebra II' },
  { code: 'MATH 3000', name: 'Real Analysis' },
  { code: 'MATH 3030', name: 'Differential Equations' },
  { code: 'MATH 3070', name: 'Partial Differential Equations' },
  { code: 'MATH 3110', name: 'Algebra I' },
  { code: 'MATH 3210', name: 'Complex Variables' },
  { code: 'MATH 3250', name: 'Introduction to Number Theory' },
  { code: 'MATH 3360', name: 'Mathematical Modelling' },
  { code: 'MATH 4000', name: 'Measure Theory and Integration' },
  { code: 'MATH 4030', name: 'Advanced Differential Equations' },

  // ===== STATISTICS =====
  { code: 'STAT 1060', name: 'Introduction to Statistics I' },
  { code: 'STAT 1061', name: 'Introduction to Statistics II' },
  { code: 'STAT 2060', name: 'Introduction to Probability and Statistics' },
  { code: 'STAT 2080', name: 'Statistics for Scientists and Engineers' },
  { code: 'STAT 3460', name: 'Probability I' },
  { code: 'STAT 3461', name: 'Probability II' },
  { code: 'STAT 3470', name: 'Regression Analysis' },
  { code: 'STAT 3480', name: 'Design of Experiments' },
  { code: 'STAT 4060', name: 'Mathematical Statistics I' },
  { code: 'STAT 4061', name: 'Mathematical Statistics II' },

  // ===== MANAGEMENT / COMMERCE =====
  { code: 'MGMT 1101', name: 'Introduction to Management' },
  { code: 'MGMT 2202', name: 'Organizational Behaviour' },
  { code: 'MGMT 2401', name: 'Marketing Management' },
  { code: 'MGMT 2601', name: 'Financial Accounting' },
  { code: 'MGMT 2602', name: 'Managerial Accounting' },
  { code: 'MGMT 3301', name: 'Strategic Management' },
  { code: 'MGMT 3401', name: 'Consumer Behaviour' },
  { code: 'MGMT 3403', name: 'Digital Marketing' },
  { code: 'MGMT 3502', name: 'Operations Management' },
  { code: 'MGMT 3601', name: 'Intermediate Financial Accounting I' },
  { code: 'MGMT 3602', name: 'Intermediate Financial Accounting II' },
  { code: 'MGMT 3701', name: 'Corporate Finance' },
  { code: 'MGMT 3702', name: 'Investment Analysis' },
  { code: 'MGMT 4201', name: 'Business Ethics' },
  { code: 'MGMT 4401', name: 'International Marketing' },
  { code: 'MGMT 4601', name: 'Advanced Accounting' },
  { code: 'MGMT 4701', name: 'Financial Derivatives' },
  { code: 'MGMT 4801', name: 'Entrepreneurship' },

  // ===== ECONOMICS =====
  { code: 'ECON 1101', name: 'Introductory Microeconomics' },
  { code: 'ECON 1102', name: 'Introductory Macroeconomics' },
  { code: 'ECON 2200', name: 'Intermediate Microeconomics' },
  { code: 'ECON 2201', name: 'Intermediate Macroeconomics' },
  { code: 'ECON 2220', name: 'Economic Statistics' },
  { code: 'ECON 2230', name: 'Introductory Econometrics' },
  { code: 'ECON 3300', name: 'Public Finance' },
  { code: 'ECON 3310', name: 'Labour Economics' },
  { code: 'ECON 3320', name: 'Industrial Organization' },
  { code: 'ECON 3330', name: 'International Trade' },
  { code: 'ECON 3340', name: 'Development Economics' },
  { code: 'ECON 4400', name: 'Advanced Microeconomics' },
  { code: 'ECON 4401', name: 'Advanced Macroeconomics' },
  { code: 'ECON 4420', name: 'Advanced Econometrics' },

  // ===== BIOLOGY =====
  { code: 'BIOL 1010', name: 'Introduction to Biology: Cells and Genetics' },
  { code: 'BIOL 1011', name: 'Introduction to Biology: Diversity and Ecology' },
  { code: 'BIOL 2020', name: 'Cell Biology' },
  { code: 'BIOL 2030', name: 'Genetics' },
  { code: 'BIOL 2040', name: 'Ecology' },
  { code: 'BIOL 2060', name: 'Molecular Biology' },
  { code: 'BIOL 2080', name: 'Comparative Animal Physiology' },
  { code: 'BIOL 2090', name: 'Plant Biology' },
  { code: 'BIOL 3010', name: 'Biochemistry' },
  { code: 'BIOL 3030', name: 'Microbiology' },
  { code: 'BIOL 3060', name: 'Evolutionary Biology' },
  { code: 'BIOL 3090', name: 'Marine Biology' },
  { code: 'BIOL 3120', name: 'Bioinformatics' },
  { code: 'BIOL 4010', name: 'Genomics' },
  { code: 'BIOL 4060', name: 'Conservation Biology' },
  { code: 'BIOL 4090', name: 'Neurobiology' },

  // ===== CHEMISTRY =====
  { code: 'CHEM 1011', name: 'General Chemistry I' },
  { code: 'CHEM 1012', name: 'General Chemistry II' },
  { code: 'CHEM 2001', name: 'Analytical Chemistry' },
  { code: 'CHEM 2003', name: 'Organic Chemistry I' },
  { code: 'CHEM 2004', name: 'Organic Chemistry II' },
  { code: 'CHEM 2401', name: 'Physical Chemistry I' },
  { code: 'CHEM 2402', name: 'Physical Chemistry II' },
  { code: 'CHEM 3400', name: 'Inorganic Chemistry' },
  { code: 'CHEM 3401', name: 'Advanced Organic Chemistry' },
  { code: 'CHEM 3402', name: 'Spectroscopy' },
  { code: 'CHEM 4001', name: 'Biochemistry I' },
  { code: 'CHEM 4002', name: 'Biochemistry II' },

  // ===== PHYSICS =====
  { code: 'PHYS 1100', name: 'Introductory Physics I' },
  { code: 'PHYS 1101', name: 'Introductory Physics II' },
  { code: 'PHYS 1300', name: 'Physics for Life Sciences I' },
  { code: 'PHYS 1301', name: 'Physics for Life Sciences II' },
  { code: 'PHYS 2000', name: 'Modern Physics' },
  { code: 'PHYS 2005', name: 'Classical Mechanics' },
  { code: 'PHYS 2010', name: 'Electricity and Magnetism' },
  { code: 'PHYS 3000', name: 'Quantum Mechanics I' },
  { code: 'PHYS 3001', name: 'Quantum Mechanics II' },
  { code: 'PHYS 3010', name: 'Thermodynamics and Statistical Mechanics' },
  { code: 'PHYS 4000', name: 'Condensed Matter Physics' },
  { code: 'PHYS 4010', name: 'Nuclear and Particle Physics' },

  // ===== ENGINEERING =====
  { code: 'ENGN 1200', name: 'Engineering Design I' },
  { code: 'ENGN 1201', name: 'Engineering Design II' },
  { code: 'ENGN 2100', name: 'Statics' },
  { code: 'ENGN 2200', name: 'Dynamics' },
  { code: 'ENGN 2212', name: 'Mechanics of Materials' },
  { code: 'ENGN 2500', name: 'Thermodynamics' },
  { code: 'ENGN 3100', name: 'Fluid Mechanics' },
  { code: 'ENGN 3110', name: 'Heat Transfer' },
  { code: 'ENGN 3200', name: 'Structural Analysis' },
  { code: 'ENGN 3300', name: 'Control Systems' },
  { code: 'ENGN 4100', name: 'Engineering Project Management' },
  { code: 'ENGN 4110', name: 'Advanced Structural Design' },

  // ===== ELECTRICAL & COMPUTER ENGINEERING =====
  { code: 'ECED 2200', name: 'Circuit Theory' },
  { code: 'ECED 2210', name: 'Digital Circuits' },
  { code: 'ECED 3200', name: 'Electronics I' },
  { code: 'ECED 3210', name: 'Electronics II' },
  { code: 'ECED 3300', name: 'Signals and Systems' },
  { code: 'ECED 3600', name: 'Embedded Systems' },
  { code: 'ECED 4200', name: 'VLSI Design' },
  { code: 'ECED 4300', name: 'Communications Engineering' },
  { code: 'ECED 4600', name: 'Computer Architecture' },

  // ===== ENGLISH =====
  { code: 'ENGL 1000', name: 'Academic Reading and Writing' },
  { code: 'ENGL 1001', name: 'Introduction to Literature' },
  { code: 'ENGL 1010', name: 'Introduction to Literature: Fiction' },
  { code: 'ENGL 1020', name: 'Introduction to Literature: Poetry' },
  { code: 'ENGL 2000', name: 'Studies in British Literature' },
  { code: 'ENGL 2001', name: 'Studies in American Literature' },
  { code: 'ENGL 2002', name: 'Studies in Canadian Literature' },
  { code: 'ENGL 2200', name: 'Shakespeare' },
  { code: 'ENGL 2300', name: 'Film Studies' },
  { code: 'ENGL 3000', name: 'Advanced Literary Theory' },
  { code: 'ENGL 3200', name: 'Postcolonial Literature' },
  { code: 'ENGL 4200', name: 'Advanced Studies in Modern Literature' },

  // ===== PSYCHOLOGY =====
  { code: 'PSYC 1011', name: 'Introductory Psychology I' },
  { code: 'PSYC 1012', name: 'Introductory Psychology II' },
  { code: 'PSYC 2000', name: 'Research Methods in Psychology' },
  { code: 'PSYC 2012', name: 'Developmental Psychology' },
  { code: 'PSYC 2021', name: 'Social Psychology' },
  { code: 'PSYC 2022', name: 'Abnormal Psychology' },
  { code: 'PSYC 2030', name: 'Biological Psychology' },
  { code: 'PSYC 2060', name: 'Cognitive Psychology' },
  { code: 'PSYC 3000', name: 'Advanced Research Methods' },
  { code: 'PSYC 3012', name: 'Child Psychopathology' },
  { code: 'PSYC 3021', name: 'Health Psychology' },
  { code: 'PSYC 3060', name: 'Perception' },
  { code: 'PSYC 4021', name: 'Clinical Psychology' },
  { code: 'PSYC 4060', name: 'Advanced Cognitive Neuroscience' },

  // ===== SOCIOLOGY =====
  { code: 'SOSA 1000', name: 'Introductory Sociology' },
  { code: 'SOSA 1002', name: 'Introductory Social Anthropology' },
  { code: 'SOSA 2000', name: 'Sociological Theory' },
  { code: 'SOSA 2100', name: 'Research Methods' },
  { code: 'SOSA 2200', name: 'Gender and Society' },
  { code: 'SOSA 3000', name: 'Advanced Sociological Theory' },
  { code: 'SOSA 3100', name: 'Race, Ethnicity and Society' },
  { code: 'SOSA 3200', name: 'Sociology of Health' },
  { code: 'SOSA 4000', name: 'Qualitative Research Methods' },

  // ===== POLITICAL SCIENCE =====
  { code: 'POLI 1000', name: 'Introduction to Political Science' },
  { code: 'POLI 1500', name: 'Introduction to International Relations' },
  { code: 'POLI 2000', name: 'Canadian Government and Politics' },
  { code: 'POLI 2200', name: 'Comparative Politics' },
  { code: 'POLI 2500', name: 'International Relations Theory' },
  { code: 'POLI 3000', name: 'Political Theory' },
  { code: 'POLI 3200', name: 'Global Governance' },
  { code: 'POLI 4000', name: 'Advanced Political Theory' },

  // ===== HISTORY =====
  { code: 'HIST 1001', name: 'Western Civilization I' },
  { code: 'HIST 1002', name: 'Western Civilization II' },
  { code: 'HIST 2010', name: 'Canadian History I' },
  { code: 'HIST 2011', name: 'Canadian History II' },
  { code: 'HIST 2200', name: 'Modern Europe' },
  { code: 'HIST 2300', name: 'History of the United States' },
  { code: 'HIST 3010', name: 'Atlantic Canada' },
  { code: 'HIST 3200', name: 'Modern World History' },
  { code: 'HIST 4010', name: 'Research Seminar in Canadian History' },

  // ===== PHILOSOPHY =====
  { code: 'PHIL 1050', name: 'Critical Thinking' },
  { code: 'PHIL 1060', name: 'Introduction to Ethics' },
  { code: 'PHIL 1080', name: 'Introduction to Philosophy' },
  { code: 'PHIL 2010', name: 'Logic' },
  { code: 'PHIL 2020', name: 'Theory of Knowledge' },
  { code: 'PHIL 2060', name: 'Social and Political Philosophy' },
  { code: 'PHIL 3010', name: 'Philosophy of Science' },
  { code: 'PHIL 3020', name: 'Philosophy of Mind' },
  { code: 'PHIL 4010', name: 'Metaphysics' },

  // ===== LAW =====
  { code: 'LAWS 1000', name: 'Legal Systems and Methods' },
  { code: 'LAWS 1001', name: 'Contracts' },
  { code: 'LAWS 1002', name: 'Torts' },
  { code: 'LAWS 1003', name: 'Property Law' },
  { code: 'LAWS 2000', name: 'Constitutional Law' },
  { code: 'LAWS 2001', name: 'Criminal Law' },
  { code: 'LAWS 2002', name: 'Administrative Law' },
  { code: 'LAWS 3000', name: 'Corporate Law' },
  { code: 'LAWS 3001', name: 'International Law' },
  { code: 'LAWS 3002', name: 'Family Law' },
  { code: 'LAWS 4000', name: 'Environmental Law' },
  { code: 'LAWS 4001', name: 'Intellectual Property Law' },

  // ===== HEALTH & KINESIOLOGY =====
  { code: 'KINE 1000', name: 'Introduction to Kinesiology' },
  { code: 'KINE 1401', name: 'Human Anatomy I' },
  { code: 'KINE 1402', name: 'Human Anatomy II' },
  { code: 'KINE 2200', name: 'Exercise Physiology' },
  { code: 'KINE 2300', name: 'Biomechanics' },
  { code: 'KINE 3200', name: 'Advanced Exercise Physiology' },
  { code: 'KINE 3300', name: 'Sport Psychology' },
  { code: 'KINE 4200', name: 'Clinical Exercise Physiology' },

  // ===== HEALTH SCIENCES =====
  { code: 'HPRO 1000', name: 'Introduction to Health' },
  { code: 'HPRO 2000', name: 'Epidemiology' },
  { code: 'HPRO 3000', name: 'Global Health' },
  { code: 'HPRO 3100', name: 'Health Policy' },

  // ===== NEUROSCIENCE =====
  { code: 'NESC 2470', name: 'Introduction to Neuroscience' },
  { code: 'NESC 3470', name: 'Systems Neuroscience' },
  { code: 'NESC 4470', name: 'Neuropharmacology' },

  // ===== DENTISTRY =====
  { code: 'DENT 1001', name: 'Oral Biology I' },
  { code: 'DENT 1002', name: 'Oral Biology II' },
  { code: 'DENT 2001', name: 'Dental Anatomy' },
  { code: 'DENT 3001', name: 'Periodontology' },

  // ===== NURSING =====
  { code: 'NURS 1000', name: 'Introduction to Nursing' },
  { code: 'NURS 2000', name: 'Health Assessment' },
  { code: 'NURS 3000', name: 'Adult Health Nursing' },
  { code: 'NURS 4000', name: 'Community Health Nursing' },

  // ===== ARCHITECTURE =====
  { code: 'ARCH 1010', name: 'Architectural Design I' },
  { code: 'ARCH 1020', name: 'Architectural Design II' },
  { code: 'ARCH 2010', name: 'Architectural History I' },
  { code: 'ARCH 2020', name: 'Structural Systems' },
  { code: 'ARCH 3010', name: 'Advanced Architectural Design' },
  { code: 'ARCH 4010', name: 'Urban Design' },

  // ===== OCEANOGRAPHY =====
  { code: 'OCEA 2000', name: 'Introduction to Oceanography' },
  { code: 'OCEA 3000', name: 'Physical Oceanography' },
  { code: 'OCEA 3100', name: 'Chemical Oceanography' },
  { code: 'OCEA 4000', name: 'Biological Oceanography' },

  // ===== ENVIRONMENTAL SCIENCE =====
  { code: 'ENVS 1000', name: 'Introduction to Environmental Science' },
  { code: 'ENVS 2000', name: 'Environmental Assessment' },
  { code: 'ENVS 3000', name: 'Climate Change Science' },
  { code: 'ENVS 4000', name: 'Environmental Policy' },

  // ===== INFORMATION MANAGEMENT =====
  { code: 'INFO 2000', name: 'Foundations of Information Management' },
  { code: 'INFO 3000', name: 'Information Architecture' },
  { code: 'INFO 3100', name: 'Digital Libraries' },
  { code: 'INFO 4000', name: 'Knowledge Management' },
];
