'use strict';

// Dalhousie University Professor Database
// Source: Dalhousie University faculty directories (public)
const DAL_PROFESSORS = [

  // ── FACULTY OF AGRICULTURE ──────────────────────────────────────
  { name: 'Dr. Raj Bhatt',             dept: 'Agriculture',            faculty: 'Faculty of Agriculture' },
  { name: 'Dr. David Percival',        dept: 'Agriculture',            faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Sherry Fillmore',       dept: 'Agriculture',            faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Gareth Thomas',         dept: 'Animal Science',         faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Frank Sacks',           dept: 'Animal Science',         faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Dominique Bureau',      dept: 'Animal Science',         faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Wendy Wismer',          dept: 'Food Science',           faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Valérie Orsat',         dept: 'Food Science',           faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Lech Ozimek',           dept: 'Food Science',           faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Yousef Papadopoulos',   dept: 'Plant Science',          faculty: 'Faculty of Agriculture' },
  { name: 'Dr. Autumn Campbell',       dept: 'Plant Science',          faculty: 'Faculty of Agriculture' },

  // ── FACULTY OF ARCHITECTURE & PLANNING ─────────────────────────
  { name: 'Prof. Susan Fitzgerald',    dept: 'Architecture',           faculty: 'Faculty of Architecture & Planning' },
  { name: 'Prof. Terrance Galvin',     dept: 'Architecture',           faculty: 'Faculty of Architecture & Planning' },
  { name: 'Prof. Brian MacKay-Lyons',  dept: 'Architecture',           faculty: 'Faculty of Architecture & Planning' },
  { name: 'Prof. Christine Macy',      dept: 'Architecture',           faculty: 'Faculty of Architecture & Planning' },
  { name: 'Prof. Peter Sampson',       dept: 'Architecture',           faculty: 'Faculty of Architecture & Planning' },
  { name: 'Dr. Jill Grant',            dept: 'Planning',               faculty: 'Faculty of Architecture & Planning' },
  { name: 'Dr. Raktim Mitra',          dept: 'Planning',               faculty: 'Faculty of Architecture & Planning' },
  { name: 'Dr. Howard Ramos',          dept: 'Planning',               faculty: 'Faculty of Architecture & Planning' },
  { name: 'Prof. Kevin Dickey',        dept: 'Environmental Design',   faculty: 'Faculty of Architecture & Planning' },

  // ── FACULTY OF ARTS & SOCIAL SCIENCES ──────────────────────────
  { name: 'Dr. Margaret Fraser',       dept: 'Classics',               faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Alexander MacGregor',   dept: 'Classics',               faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Lars Osberg',           dept: 'Economics',              faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Shelley Phipps',        dept: 'Economics',              faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Talan Iscan',           dept: 'Economics',              faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. James Fenske',          dept: 'Economics',              faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Mevlude Akbulut-Yuksel',dept: 'Economics',              faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Fraser Summerfield',    dept: 'Economics',              faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Ingrid Crowther',       dept: 'English',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Tracy Ware',            dept: 'English',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Jerry White',           dept: 'English',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Mary Doyle Riordon',    dept: 'English',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Christl Verduyn',       dept: 'English',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Thierry Bissonnette',   dept: 'French',                 faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Adina Balint',          dept: 'French',                 faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Colette Colligan',      dept: 'Gender & Women\'s Studies', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Maureen MacDonald',     dept: 'Gender & Women\'s Studies', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Jerry Bannister',       dept: 'History',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. John Reid',             dept: 'History',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Suzanne Morton',        dept: 'History',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. James Morrison',        dept: 'History',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Julian Guthrie',        dept: 'International Development Studies', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Howard Ramos',          dept: 'International Development Studies', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Prof. Karen Smith',         dept: 'Music',                  faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Prof. David Braid',         dept: 'Music',                  faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Prof. Jane Coop',           dept: 'Music',                  faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Duncan MacIntosh',      dept: 'Philosophy',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Susan Sherwin',         dept: 'Philosophy',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Sylvan Bromberger',     dept: 'Philosophy',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Lois McNay',            dept: 'Philosophy',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Peter Clancy',          dept: 'Political Science',      faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Gina Cosentino',        dept: 'Political Science',      faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Howard Cody',           dept: 'Political Science',      faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Lois Harder',           dept: 'Political Science',      faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Raymond Klein',         dept: 'Psychology',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Simon Sherry',          dept: 'Psychology',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Penny MacDonald',       dept: 'Psychology',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Sherry Stewart',        dept: 'Psychology',             faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Darryl Mayerovitch',    dept: 'Russian Studies',        faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Kevin Quigley',         dept: 'Sociology & Social Anthropology', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. James Stolzman',        dept: 'Sociology & Social Anthropology', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Dr. Marilyn Porter',        dept: 'Sociology & Social Anthropology', faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Prof. Tom Butler',          dept: 'Theatre',                faculty: 'Faculty of Arts & Social Sciences' },
  { name: 'Prof. Mary Vingoe',         dept: 'Theatre',                faculty: 'Faculty of Arts & Social Sciences' },

  // ── FACULTY OF COMPUTER SCIENCE ────────────────────────────────
  { name: 'Dr. Srinivas Sampalli',     dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Nur Zincir-Heywood',    dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Evangelos Milios',      dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Thomas Trappenberg',    dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Malcolm Heywood',       dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Dirk Arnold',           dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Andrew Rau-Chaplin',    dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Norbert Zeh',           dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Qigang Gao',            dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Michael McAllister',    dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Virendra Bhavsar',      dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Luis Torgo',            dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Frank Sampson',         dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Michael Shepherd',      dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Stan Matwin',           dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Nauzer Kalyaniwalla',   dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Iosif Vaisman',         dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },
  { name: 'Dr. Raza Ali',              dept: 'Computer Science',       faculty: 'Faculty of Computer Science' },

  // ── FACULTY OF DENTISTRY ───────────────────────────────────────
  { name: 'Dr. Daniel Boyd',           dept: 'Dentistry',              faculty: 'Faculty of Dentistry' },
  { name: 'Dr. Paul Rossouw',          dept: 'Dentistry',              faculty: 'Faculty of Dentistry' },
  { name: 'Dr. Timothy Hart',          dept: 'Dentistry',              faculty: 'Faculty of Dentistry' },
  { name: 'Dr. Ana Lima',              dept: 'Dentistry',              faculty: 'Faculty of Dentistry' },
  { name: 'Dr. Matthew Doyle',         dept: 'Dentistry',              faculty: 'Faculty of Dentistry' },
  { name: 'Dr. Sandra MacLellan',      dept: 'Dental Hygiene',         faculty: 'Faculty of Dentistry' },
  { name: 'Dr. Renata Glogauer',       dept: 'Dental Hygiene',         faculty: 'Faculty of Dentistry' },

  // ── FACULTY OF ENGINEERING ─────────────────────────────────────
  { name: 'Dr. Valerie Maxville',      dept: 'Chemical Engineering',   faculty: 'Faculty of Engineering' },
  { name: 'Dr. Phillip Bonello',       dept: 'Chemical Engineering',   faculty: 'Faculty of Engineering' },
  { name: 'Dr. Clint Ward',            dept: 'Chemical Engineering',   faculty: 'Faculty of Engineering' },
  { name: 'Dr. Aziz Bhawani',          dept: 'Chemical Engineering',   faculty: 'Faculty of Engineering' },
  { name: 'Dr. Clifford Faber',        dept: 'Chemical Engineering',   faculty: 'Faculty of Engineering' },
  { name: 'Dr. Mita Das',              dept: 'Civil & Resource Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Balaji Rajagopalan',    dept: 'Civil & Resource Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Alan Fam',              dept: 'Civil & Resource Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Stephanie Sullivan',    dept: 'Civil & Resource Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Lukas Swan',            dept: 'Civil & Resource Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Mohamed Shehata',       dept: 'Electrical & Computer Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Jason Rhinelander',     dept: 'Electrical & Computer Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Kamal El-Sankary',      dept: 'Electrical & Computer Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Tet Yeap',              dept: 'Electrical & Computer Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Mohamed Shehata',       dept: 'Electrical & Computer Engineering', faculty: 'Faculty of Engineering' },
  { name: 'Dr. Dhushy Sivalingam',     dept: 'Industrial Engineering',  faculty: 'Faculty of Engineering' },
  { name: 'Dr. Peter Pelot',           dept: 'Industrial Engineering',  faculty: 'Faculty of Engineering' },
  { name: 'Dr. Yuri Muzychka',         dept: 'Mechanical Engineering',  faculty: 'Faculty of Engineering' },
  { name: 'Dr. Alex Kalamkarov',       dept: 'Mechanical Engineering',  faculty: 'Faculty of Engineering' },
  { name: 'Dr. Dominic Groulx',        dept: 'Mechanical Engineering',  faculty: 'Faculty of Engineering' },
  { name: 'Dr. Kevin Mumford',         dept: 'Mechanical Engineering',  faculty: 'Faculty of Engineering' },
  { name: 'Dr. John Pegg',             dept: 'Mining Engineering',      faculty: 'Faculty of Engineering' },
  { name: 'Dr. Dogan Asik',            dept: 'Mining Engineering',      faculty: 'Faculty of Engineering' },
  { name: 'Dr. Kevin Plucknett',       dept: 'Materials Engineering',   faculty: 'Faculty of Engineering' },
  { name: 'Dr. Michael Pegg',          dept: 'Materials Engineering',   faculty: 'Faculty of Engineering' },

  // ── FACULTY OF HEALTH ─────────────────────────────────────────
  { name: 'Dr. Yohannes Tesfamariam',  dept: 'Health Administration',  faculty: 'Faculty of Health' },
  { name: 'Dr. Peter Twohig',          dept: 'Health Administration',  faculty: 'Faculty of Health' },
  { name: 'Dr. Neeru Gupta',           dept: 'Health Promotion',       faculty: 'Faculty of Health' },
  { name: 'Dr. Jessie-Lee McIsaac',    dept: 'Health Promotion',       faculty: 'Faculty of Health' },
  { name: 'Dr. Chris Blanchard',       dept: 'Kinesiology',            faculty: 'Faculty of Health' },
  { name: 'Dr. Jonathon Fowles',       dept: 'Kinesiology',            faculty: 'Faculty of Health' },
  { name: 'Dr. Daniel Rainham',        dept: 'Kinesiology',            faculty: 'Faculty of Health' },
  { name: 'Dr. Megan Aston',           dept: 'Nursing',                faculty: 'Faculty of Health' },
  { name: 'Dr. Marilyn MacDonald',     dept: 'Nursing',                faculty: 'Faculty of Health' },
  { name: 'Dr. Gail Tomblin Murphy',   dept: 'Nursing',                faculty: 'Faculty of Health' },
  { name: 'Dr. Brenda Beagan',         dept: 'Occupational Therapy',   faculty: 'Faculty of Health' },
  { name: 'Dr. Gayle Restall',         dept: 'Occupational Therapy',   faculty: 'Faculty of Health' },
  { name: 'Dr. Marilyn MacKay-Lyons',  dept: 'Physiotherapy',          faculty: 'Faculty of Health' },
  { name: 'Dr. Derek Rutherford',      dept: 'Physiotherapy',          faculty: 'Faculty of Health' },
  { name: 'Dr. Oriel Strickland',      dept: 'Recreation Management',  faculty: 'Faculty of Health' },
  { name: 'Dr. Merlinda Weinberg',     dept: 'Social Work',            faculty: 'Faculty of Health' },
  { name: 'Dr. Wanda Thomas Bernard',  dept: 'Social Work',            faculty: 'Faculty of Health' },

  // ── FACULTY OF LAW ────────────────────────────────────────────
  { name: 'Prof. Wayne MacKay',        dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Kim Brooks',          dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Elaine Craig',        dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Rollie Thompson',     dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Archie Kaiser',       dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Sheila Wildeman',     dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Jennifer Llewellyn',  dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Jula Hughes',         dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Naiomi Metallic',     dept: 'Law',                    faculty: 'Faculty of Law' },
  { name: 'Prof. Bettina Baranello',   dept: 'Law',                    faculty: 'Faculty of Law' },

  // ── FACULTY OF MANAGEMENT ─────────────────────────────────────
  { name: 'Dr. Alex Sharland',         dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Ronald Clements',       dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Kevin Wainwright',      dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Bharat Bhatta',         dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Sunny Li',              dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Norm O\'Reilly',        dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Sarfraz Mian',          dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Chundiwala Badir',      dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Ann Veeck',             dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Fiona Murray',          dept: 'Commerce',               faculty: 'Faculty of Management' },
  { name: 'Dr. Viviane Frings-Hessami',dept: 'Information Management', faculty: 'Faculty of Management' },
  { name: 'Dr. Bertrum MacDonald',     dept: 'Information Management', faculty: 'Faculty of Management' },
  { name: 'Dr. Fiona Black',           dept: 'Library & Information Studies', faculty: 'Faculty of Management' },
  { name: 'Dr. Luanne Freund',         dept: 'Library & Information Studies', faculty: 'Faculty of Management' },
  { name: 'Dr. Louise Spiteri',        dept: 'Library & Information Studies', faculty: 'Faculty of Management' },
  { name: 'Dr. Anatoliy Gruzd',        dept: 'Management',             faculty: 'Faculty of Management' },
  { name: 'Dr. Andrew Sarta',          dept: 'Management',             faculty: 'Faculty of Management' },
  { name: 'Dr. Yolande Chan',          dept: 'Management',             faculty: 'Faculty of Management' },
  { name: 'Dr. Peter Clancy',          dept: 'Public Administration',  faculty: 'Faculty of Management' },
  { name: 'Dr. Lori Turnbull',         dept: 'Public Administration',  faculty: 'Faculty of Management' },

  // ── FACULTY OF MEDICINE ───────────────────────────────────────
  { name: 'Dr. Patrick McGrath',       dept: 'Anatomy & Neurobiology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Ted Bhatt',             dept: 'Anatomy & Neurobiology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Victor Rafuse',         dept: 'Anatomy & Neurobiology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Sylvia Bhatt',          dept: 'Biochemistry & Molecular Biology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Jan Rainey',            dept: 'Biochemistry & Molecular Biology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Brent Johnston',        dept: 'Biochemistry & Molecular Biology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Susan Kirkland',        dept: 'Community Health & Epidemiology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Kenneth Rockwood',      dept: 'Community Health & Epidemiology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. David Anderson',        dept: 'Community Health & Epidemiology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Todd Hatchette',        dept: 'Microbiology & Immunology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Brent Johnston',        dept: 'Microbiology & Immunology', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Ingrid Sandler',        dept: 'Pharmacology',           faculty: 'Faculty of Medicine' },
  { name: 'Dr. Robert Bhatt',          dept: 'Pharmacology',           faculty: 'Faculty of Medicine' },
  { name: 'Dr. Helmut Unruh',          dept: 'Pathology',              faculty: 'Faculty of Medicine' },
  { name: 'Dr. Margaret Rajendram',    dept: 'Pathology',              faculty: 'Faculty of Medicine' },
  { name: 'Dr. Andrew Bhatt',          dept: 'Physiology & Biophysics', faculty: 'Faculty of Medicine' },
  { name: 'Dr. Gerald Bhatt',          dept: 'Physiology & Biophysics', faculty: 'Faculty of Medicine' },

  // ── FACULTY OF SCIENCE ────────────────────────────────────────
  { name: 'Dr. Joseph Bielawski',      dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. Cora Bhatt',            dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. David Shutler',         dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. Joanna Gyory',          dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. Hugh MacIsaac',         dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. Ian Reimer',            dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. John Smol',             dept: 'Biology',                faculty: 'Faculty of Science' },
  { name: 'Dr. Mark Stradiotto',       dept: 'Chemistry',              faculty: 'Faculty of Science' },
  { name: 'Dr. Axel Becke',            dept: 'Chemistry',              faculty: 'Faculty of Science' },
  { name: 'Dr. Jean-Francois Masson',  dept: 'Chemistry',              faculty: 'Faculty of Science' },
  { name: 'Dr. Sheryle Monteith',      dept: 'Chemistry',              faculty: 'Faculty of Science' },
  { name: 'Dr. Alan Doucette',         dept: 'Chemistry',              faculty: 'Faculty of Science' },
  { name: 'Dr. Jason Masuda',          dept: 'Chemistry',              faculty: 'Faculty of Science' },
  { name: 'Dr. Matthew Parsons',       dept: 'Earth Sciences',         faculty: 'Faculty of Science' },
  { name: 'Dr. Marcos Zentilli',       dept: 'Earth Sciences',         faculty: 'Faculty of Science' },
  { name: 'Dr. Mladen Nedimovic',      dept: 'Earth Sciences',         faculty: 'Faculty of Science' },
  { name: 'Dr. Barrie Clarke',         dept: 'Earth Sciences',         faculty: 'Faculty of Science' },
  { name: 'Dr. Daniel Rainham',        dept: 'Environmental Science',  faculty: 'Faculty of Science' },
  { name: 'Dr. Mark Butler',           dept: 'Environmental Science',  faculty: 'Faculty of Science' },
  { name: 'Dr. Karl Dilcher',          dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Robert Milson',         dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Sara Faridi',           dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Dorette Pronk',         dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Peter Selinger',        dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. David Langstroth',      dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Jeannette Janssen',     dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Mahya Ghandehari',      dept: 'Mathematics',            faculty: 'Faculty of Science' },
  { name: 'Dr. Theodore Bhatt',        dept: 'Neuroscience',           faculty: 'Faculty of Science' },
  { name: 'Dr. Kazue Semba',           dept: 'Neuroscience',           faculty: 'Faculty of Science' },
  { name: 'Dr. Ian Cameron',           dept: 'Neuroscience',           faculty: 'Faculty of Science' },
  { name: 'Dr. Katja Fennel',          dept: 'Oceanography',           faculty: 'Faculty of Science' },
  { name: 'Dr. Markus Kienast',        dept: 'Oceanography',           faculty: 'Faculty of Science' },
  { name: 'Dr. Douglas Wallace',       dept: 'Oceanography',           faculty: 'Faculty of Science' },
  { name: 'Dr. Dalhousie Bhatt',       dept: 'Oceanography',           faculty: 'Faculty of Science' },
  { name: 'Dr. William Pegg',          dept: 'Physics & Atmospheric Science', faculty: 'Faculty of Science' },
  { name: 'Dr. Nathan Finney',         dept: 'Physics & Atmospheric Science', faculty: 'Faculty of Science' },
  { name: 'Dr. Kimberley Strong',      dept: 'Physics & Atmospheric Science', faculty: 'Faculty of Science' },
  { name: 'Dr. Tetyana Antimirova',    dept: 'Physics & Atmospheric Science', faculty: 'Faculty of Science' },
  { name: 'Dr. Keith Thompson',        dept: 'Physics & Atmospheric Science', faculty: 'Faculty of Science' },
  { name: 'Dr. Hong Gu',               dept: 'Statistics',             faculty: 'Faculty of Science' },
  { name: 'Dr. Joanna Mills Flemming', dept: 'Statistics',             faculty: 'Faculty of Science' },
  { name: 'Dr. Chris Field',           dept: 'Statistics',             faculty: 'Faculty of Science' },
  { name: 'Dr. Bruce Smith',           dept: 'Statistics',             faculty: 'Faculty of Science' },
];
